package com.mycompany.chservicetime.model;

/**
 * Created by szhx on 12/13/2015.
 */
public class TimeSlot {

    public static int INVALID_ID = -1;

    public int id;
    public String timeSlotId;
    public String name;
    public String description;
    public Integer beginTimeHour;
    public Integer beginTimeMinute;
    public Integer endTimeHour;
    public Integer endTimeMinute;
    public String days;
    public Boolean repeatFlag;
    public Boolean activationFlag;
    public long updatedTimestamp;

    public TimeSlot() {
    }

    /**
     * Use this constructor to create a new TimeSlot
     */
    public TimeSlot(int id, String timeSlotId, String name, String description,
                    Integer beginTimeHour, Integer beginTimeMinute, Integer endTimeHour, Integer endTimeMinute,
                    String days, Boolean repeatFlag, Boolean activationFlag, long updatedTimestamp) {
        this.id = id;
        this.timeSlotId = timeSlotId;
        this.beginTimeHour = beginTimeHour;
        this.beginTimeMinute = beginTimeMinute;
        this.days = days;
        this.endTimeHour = endTimeHour;
        this.endTimeMinute = endTimeMinute;
        this.name = name;
        this.description = description;
        this.repeatFlag = repeatFlag;
        this.activationFlag = activationFlag;
        this.updatedTimestamp = updatedTimestamp;
    }

    /**
     * Use this constructor to create a TimeSlot with all basic data.
     */
    public TimeSlot(String timeSlotId, String name, String description,
                    Integer beginTimeHour, Integer beginTimeMinute, Integer endTimeHour, Integer endTimeMinute,
                    String days, Boolean repeatFlag) {
        this(INVALID_ID, timeSlotId, name, description,
                beginTimeHour, beginTimeMinute, endTimeHour, endTimeMinute,
                days, repeatFlag, null, 0L);
    }

    public boolean compare(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        TimeSlot timeSlot = (TimeSlot) o;

        /**
         * id is generated by DB and it will change, so we do not compare it.
         */
        //if (id != timeSlot.id) return false;
        /**
         * updatedTimestamp changes every time, so we do not compare it.
         */
        //if (updatedTimestamp != timeSlot.updatedTimestamp) return false;
        if (beginTimeHour != timeSlot.beginTimeHour) return false;
        if (beginTimeMinute != timeSlot.beginTimeMinute) return false;
        if (endTimeHour != timeSlot.endTimeHour) return false;
        if (endTimeMinute != timeSlot.endTimeMinute) return false;
        if (repeatFlag != timeSlot.repeatFlag) return false;
        if (timeSlotId != null ? !timeSlotId.equals(timeSlot.timeSlotId) : timeSlot.timeSlotId != null)
            return false;
        if (name != null ? !name.equals(timeSlot.name) : timeSlot.name != null) return false;
        if (description != null ? !description.equals(timeSlot.description) : timeSlot.description != null)
            return false;
        return days != null ? days.equals(timeSlot.days) : timeSlot.days == null;

    }


}
